services:
  - type: web
    name: download-media
    runtime: python
    buildCommand: apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
